[package]
name = "Janlib"
version = "0.1.1"
edition = "2024"
authors = ["github: https://github.com/Yop1-BSecretKikx/Janlib.git"]
description = "Simulate key press and mouse movement on macOS"
license = "MIT"
readme = "README.md"

[dependencies]
core-graphics = "0.25.0"
thread = "0.0.1"
